advantage_point:
  outputs:
    dev:
      dbname: "{{ env_var('DBT_DATABASE') }}"
      host: "{{ env_var('DBT_HOST') }}"
      password: "{{ env_var('DBT_PASSWORD') }}" 
      port: "{{ env_var('DBT_PORT') | int }}"
      schema: "{{ env_var('DBT_SCHEMA') }}"
      threads: "{{ env_var('DBT_THREADS', 4) | int }}"
      type: "{{ env_var('DBT_DATABASE_TYPE') }}"
      user: "{{ env_var('DBT_USER') }}"
  target: dev
