name: Setup Ingestion Environment
description: Setup environment and dependencies for ingestion layer

runs:
  using: "composite"
  steps:
    - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.ENVIRONMENT == 'prod' && 'master' || 'dev' }}

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      shell: bash
      run: |
        pip install -r ingest/requirements.txt