name: Setup Ingestion Environment
description: Setup environment and dependencies for ingestion layer
inputs:
  chrome-version
    description: "Chrome version to install"
    required: false
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Dependencies
      shell: bash
      run: |
        pip install -r ingest/requirements.txt

    - name: Remove old Chrome if it exists
      shell: bash
      run: |
        sudo apt-get remove -y google-chrome-stable || true  # Ignore error if Chrome is not installed

    - name: Install chrome
      id: setup-chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: ${{ inputs.chrome-version }}
        install-chromedriver: true

outputs:
  chromedriver-path: ${{ steps.setup-chrome.outputs.chromedriver-path }}