name: Setup Ingestion Environment
description: Setup environment and dependencies for ingestion layer
inputs:
  chrome-version:
    description: "Chrome version to install"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Dependencies
      shell: bash
      run: |
        pip install -r ingest/requirements.txt