name: Run Data Warehouse

on:
#   schedule:
#     - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to run the script'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

jobs:
  run_script:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.environment == 'prod' && 'master' || 'dev' }}

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'   
          
      - name: Run python script
        env:
          DATABASE: ${{ vars.DATABASE }}
          USER: ${{ vars.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          HOST: ${{ vars.HOST }}
          PORT: ${{ vars.PORT }}
        run: |
          python -m warehouse.warehouse_main
