name: Run dbt

on:
  workflow_dispatch:

env:
  DBT_DATABASE: ${{ vars.SUPABASE_DATABASE }}
  DBT_HOST: ${{ vars.SUPABASE_HOST }}
  DBT_PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
  DBT_PORT: ${{ vars.SUPABASE_PORT }}
  DBT_SCHEMA: ${{ vars.DBT_SCHEMA }}
  DBT_SCHEMA_INGESTION: ${{ vars.SCHEMA_INGESTION }}
  DBT_SCHEMA_SEED: ${{ vars.SCHEMA_SEED }}
  DBT_SCHEMA_STAGING: ${{ vars.SCHEMA_STAGING }}
  DBT_THREADS: ${{ vars.DBT_THREADS }}
  DBT_USER: ${{ vars.SUPABASE_USER }}
  type: postgres

jobs:
  run_dbt:
    name: Run dbt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requirements
        run:
          pip install -r dbt/requirements.txt

      - name: Run dbt commands
        run: |
          dbt deps --project-dir dbt/advantage_point &&
          dbt seed --full-refresh --profiles-dir ./dbt --project-dir dbt/advantage_point &&
          dbt build --profiles-dir ./dbt --project-dir dbt/advantage_point


