name: Run Data Warehouse

on:
#   schedule:
#     - cron: '0 0 * * *'
  push:
    branches:
      - dev

jobs:
  run_script:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'    

      - name: Set environment variables

      - name: Debug environment variables
        run: |
          echo "DATABASE=${{ vars.DATABASE }}"
