name: Run Data Warehouse

on:
#   schedule:
#     - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to run the script'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

jobs:
  run_script:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.SUPER_PASSWORD }}
          POSTGRES_DB: ${{ vars.DATABASE }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.environment == 'prod' && 'master' || 'dev' }}

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          
      - name: Run python script
        env:
          DATABASE: ${{ vars.DATABASE }}
          USER: postgres
          PASSWORD: ${{ secrets.SUPER_PASSWORD }}
          HOST: localhost
          PORT: 5432
        run: |
          python -m warehouse.warehouse_main
