name: Run Data Warehouse

on:
#   schedule:
#     - cron: '0 0 * * *'
  push:
    branches:
      - dev

jobs:
  run_script:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.environment == 'prod' && 'master' || 'dev' }}

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'   

      - name: Set environment variables
        env:
          DATABASE: ${{ vars.DATABASE }}
        run: |
          echo "Current environment: ${{ matrix.environment }}"
          echo "DATABASE=${DATABASE}"
