name: Run Data Warehouse

on:
#   schedule:
#     - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to run the script'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

jobs:
  run_script:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.environment == 'prod' && 'master' || 'dev' }}

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

          sudo apt-get update
          sudo apt-get install -y wget unzip
          
          # Install a specific version of Chrome (e.g., version 114)
          CHROME_VERSION="114.0.5735.90"  # Use the specific Chrome version
          echo "Installing Google Chrome Version: $CHROME_VERSION"
          
          wget "https://dl.google.com/linux/direct/google-chrome-stable_${CHROME_VERSION}_amd64.deb"
          sudo dpkg -i "google-chrome-stable_${CHROME_VERSION}_amd64.deb" || sudo apt-get -f install
          
          # Fetch ChromeDriver for the exact version of Chrome installed
          CHROMEDRIVER_VERSION="114.0.5735.90"  # Ensure this matches the Chrome version
          echo "Fetching ChromeDriver for Version: $CHROMEDRIVER_VERSION"
          
          # Download and install the matching ChromeDriver version
          wget "https://chromedriver.storage.googleapis.com/${CHROMEDRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          
          # Create directory if it doesn't exist and move chromedriver
          mkdir -p $(dirname "${{ vars.CHROMEDRIVER_PATH }}")
          sudo mv chromedriver ${{ vars.CHROMEDRIVER_PATH }}
          sudo chmod +x ${{ vars.CHROMEDRIVER_PATH }}
            
      - name: Run python script
        env:
          CHROMEDRIVER_PATH: ${{ vars.CHROMEDRIVER_PATH }}
          DATABASE: ${{ vars.SUPABASE_DATABASE }}
          HOST: ${{ vars.SUPABASE_HOST }}
          PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          PORT: ${{ vars.SUPABASE_PORT }}
          SCHEMA_INGESTION: ${{ vars.SCHEMA_INGESTION }}
          SCHEMA_PRESENTATION: ${{ vars.SCHEMA_PRESENTATION }}
          SCHEMA_STAGING: ${{ vars.SCHEMA_STAGING }}
          SCHEMA_TRANSFORMATION: ${{ vars.SCHEMA_TRANSFORMATION }}
          USER: ${{ vars.SUPABASE_USER }}
        run: |
          python -m warehouse.warehouse_main
