# Consolidated Workflow: .github/workflows/setup_and_run_warehouse.yml
name: Run Data Warehouse

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to run the script'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

jobs:
  setup:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.environment == 'prod' && 'master' || 'dev' }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python requirements
        run: |
          pip install -r requirements.txt

      - name: Remove old Chrome if it exists
        run: |
          sudo apt-get remove -y google-chrome-stable || true  # Ignore error if Chrome is not installed

      - name: Install Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: ${{ vars.CHROME_VERSION }}
          install-chromedriver: true

  run-script:
    runs-on: ubuntu-latest
    needs: setup
    environment: ${{ github.event.inputs.environment }}

    steps:

      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.environment == 'prod' && 'master' || 'dev' }}
      
      - name: Run Python script
        env:
          CHROMEDRIVER_PATH: ${{ steps.setup-chrome.outputs.chromedriver-path }}
          DATABASE: ${{ vars.SUPABASE_DATABASE }}
          HOST: ${{ vars.SUPABASE_HOST }}
          PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          PORT: ${{ vars.SUPABASE_PORT }}
          SCHEMA_INGESTION: ${{ vars.SCHEMA_INGESTION }}
          SCHEMA_PRESENTATION: ${{ vars.SCHEMA_PRESENTATION }}
          SCHEMA_STAGING: ${{ vars.SCHEMA_STAGING }}
          SCHEMA_TRANSFORMATION: ${{ vars.SCHEMA_TRANSFORMATION }}
          USER: ${{ vars.SUPABASE_USER }}
        run: |
          python -m warehouse.warehouse_main
