name: Run Data Warehouse

on:
#   schedule:
#     - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to run the script'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

jobs:
  create-ingestion-schemas:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.environment == 'prod' && 'master' || 'dev' }}

      - name: Setup environment
        uses: ./.github/actions/setup/ingestion

      - name: Set schema variables
        run: |
          # Start by setting the SCHEMA_INGESTION variable from the environment variable
          SCHEMA_INGESTION="${{ vars.SCHEMA_INGESTION }}"
          SCHEMA_INGESTION_TEMP="${SCHEMA_INGESTION}_temp"

          # Modify the schema names if the environment is 'dev'
          if [ "${{ github.event.inputs.environment }}" == "dev" ]; then
            SCHEMA_INGESTION="${SCHEMA_INGESTION}_dev"
            SCHEMA_INGESTION_TEMP="${SCHEMA_INGESTION_TEMP}_dev"
          fi

          # Export the variables to be used in subsequent steps
          echo "SCHEMA_INGESTION=$SCHEMA_INGESTION" >> $GITHUB_ENV
          echo "SCHEMA_INGESTION_TEMP=$SCHEMA_INGESTION_TEMP" >> $GITHUB_ENV

      - name: Create schemas
        env:
          DATABASE: ${{ vars.SUPABASE_DATABASE }}
          HOST: ${{ vars.SUPABASE_HOST }}
          PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          PORT: ${{ vars.SUPABASE_PORT }}
          SCHEMA_INGESTION: ${{ env.SCHEMA_INGESTION }}
          SCHEMA_INGESTION_TEMP: ${{ env.SCHEMA_INGESTION_TEMP }}
          USER: ${{ vars.SUPABASE_USER }}
        run: |
          echo "Creating schemas"
          python -m ingest.create_ingestion_schemas


  run-ingestion-scripts:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}
    strategy:
      matrix:
        scripts:
          - name: ingest_players_tennisabstract
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.environment == 'prod' && 'master' || 'dev' }}

      - name: Setup environment
        id: setup-env
        uses: ./.github/actions/setup/ingestion
      
      - name: Run ingestion script
        env:
          CHROMEDRIVER_PATH: ${{ steps.setup-env.outputs.chromedriver-path }}
          DATABASE: ${{ vars.SUPABASE_DATABASE }}
          HOST: ${{ vars.SUPABASE_HOST }}
          PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          PORT: ${{ vars.SUPABASE_PORT }}
          SCHEMA_INGESTION: ${{ env.SCHEMA_INGESTION }}
          SCHEMA_INGESTION_TEMP: ${{ env.SCHEMA_INGESTION_TEMP }}
          USER: ${{ vars.SUPABASE_USER }}
        run: |
          echo "Running ingestion script: ${{ matrix.scripts.name }}"
          python -m ingest.${{ matrix.scripts.name }}
