name: Run Data Warehouse

on:
#   schedule:
#     - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'    

      - name: Set environment variables
        env:
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
            echo "PASSWORD = $PASSWORD"
