name: Run Data Warehouse

on:
#   schedule:
#     - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Select the environment to run the script'
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod

jobs:
  run_script:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.environment == 'prod' && 'master' || 'dev' }}

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install python requirements
        run: |
          pip install -r requirements.txt

      - name: Install chrome and chromedriver
        id: chrome_setup
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 120
          install-chromedriver: true

      - name: Run python script
        env:
          CHROMEDRIVER_PATH: ${{ steps.chrome_setup.outputs.chromedriver-path }}
          DATABASE: ${{ vars.SUPABASE_DATABASE }}
          HOST: ${{ vars.SUPABASE_HOST }}
          PASSWORD: ${{ secrets.SUPABASE_PASSWORD }}
          PORT: ${{ vars.SUPABASE_PORT }}
          SCHEMA_INGESTION: ${{ vars.SCHEMA_INGESTION }}
          SCHEMA_PRESENTATION: ${{ vars.SCHEMA_PRESENTATION }}
          SCHEMA_STAGING: ${{ vars.SCHEMA_STAGING }}
          SCHEMA_TRANSFORMATION: ${{ vars.SCHEMA_TRANSFORMATION }}
          USER: ${{ vars.SUPABASE_USER }}
        run: |
          python -m warehouse.warehouse_main
