version: 2

sources:
  - name: tennisabstract
    description: Data obtained from tennisabstract.com
    tables:
      - name: match_points
        identifier: tennisabstract_match_points
      - name: matches
        identifier: tennisabstract_matches
      - name: players
        identifier: tennisabstract_players