version: 2

sources:
  - name: tennisabstract
    schema: "{{ env_var('DBT_SCHEMA_INGESTION') }}"
    description: Data obtained from tennisabstract.com via web scraping.
    tables:
      - name: match_points
        identifier: tennisabstract_match_points
        description: Contain match points that exist on the site.

      - name: matches
        identifier: tennisabstract_matches
        description: Contain matches that exist on the site.

      - name: players
        identifier: tennisabstract_players
        description: Contain players that exist on the site.
        
      - name: tournaments
        identifier: tennisabstract_tournaments
        description: Contain tournaments that exist on the site.